config/routes.rb
Education::Application.routes.draw do
  resources :users
  resources :sessions, only: [:new, :create, :destroy]
  resources :microposts, only: [:create, :destroy]

  root                to: 'static_pages#home'
  match '/help'     , to: 'static_pages#help'
  match '/signup'   , to: 'users#new'
  match '/signin'   , to: 'sessions#new'
  match '/signout'  , to: 'sessions#destroy', via: :delete

end

app/models/micropost.rb
# == Schema Information
#
# Table name: microposts
#
#  id         :integer          not null, primary key
#  content    :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Micropost < ActiveRecord::Base
  attr_accessible :content
  belongs_to :user
  
  validates :user_id, presence: true
  validates :content, presence: true, length: { maximum: 140 }
  
  default_scope order: 'microposts.created_at DESC'
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  name            :string(255)
#  email           :string(255)
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#  password_digest :string(255)
#  remember_token  :string(255)
#  admin           :boolean          default(FALSE)
#

class User < ActiveRecord::Base
  attr_accessible :name, :email, :password, :password_confirmation

  has_secure_password
  has_many :microposts, dependent: :destroy

  # before_save { email.downcase! }
  before_save { |user| user.email = email.downcase }
  before_save :create_remember_token
  
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence:   true,
                    format:     { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  validates :password, presence: true, length: { minimum: 6 }
  validates :password_confirmation, presence: true
  

  private

    def create_remember_token
      self.remember_token = SecureRandom.urlsafe_base64
    end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  include SessionsHelper

  # Force signout to prevent CSRF attacks
  def handle_unverified_request
    sign_out
    super
  end
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
  before_filter :signed_in_user, only: [:create, :destroy]
  before_filter :correct_user,   only: :destroy

  def create
    @micropost = current_user.microposts.build(params[:micropost])
    if @micropost.save
      flash[:success] = "Micropost created!"
      redirect_to root_url
    else
      @feed_items = []
      render 'static_pages/home'
    end
  end

  def destroy
    @micropost.destroy
    redirect_to root_url
  end

  private

    def correct_user
      @micropost = current_user.microposts.find_by_id(params[:id])
      redirect_to root_url if @micropost.nil?
    end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

	def new
		
	end

  def create
    user = User.find_by_email(params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      sign_in user
      redirect_back_or user
    else
      flash.now[:danger] = 'Invalid email/password combination'
      render 'new'
    end
  end

  def destroy
    sign_out
    redirect_to root_url
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if signed_in?
      @micropost  = current_user.microposts.build
      @feed_items = current_user.microposts.paginate(page: params[:page])
    end
  end
  
  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :signed_in_user ,  only: [:index, :edit, :update, :destroy]
  before_filter :correct_user   ,  only: [:edit, :update]
  before_filter :admin_user     ,  only: :destroy
  def index
    @users = User.paginate(page: params[:page])
  end

  def new
  	@user = User.new
  end

  def show
  	@user = User.find(params[:id])
    @microposts = @user.microposts.paginate(page: params[:page])
  end

  def create
    @user = User.new(params[:user])
    if @user.save
      sign_in @user
      flash[:success] = "Welcome to the Sample App!"
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    User.find(params[:id]).destroy
    flash[:success] = "User destroyed."
    redirect_to users_url
  end

  def edit
  end

  def update
    # @user = User.find(params[:id])
    if @user.update_attributes(params[:user])
      flash[:success] = "Profile updated"
      sign_in @user
      redirect_to @user
    else
      render 'edit'
    end
  end
  

  def feed
    # Это предварительное решение. См. полную реализацию в "Following users".
    Micropost
  end

  private

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_path) unless current_user?(@user)
    end

    def admin_user
      redirect_to(root_path) unless current_user.admin?
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
	# returns title for page
	def title(page_title)
		base_title = "Education"
		if page_title.empty?
			base_title
		else
			"#{base_title} | #{page_title}"
		end
	end
end

app/helpers/microposts_helper.rb
module MicropostsHelper
	def wrap(content)
    sanitize(raw(content.split.map{ |s| wrap_long_string(s) }.join(' ')))
  end

  private

    def wrap_long_string(text, max_width = 30)
      zero_width_space = "&#8203;"
      regex = /.{1,#{max_width}}/
      (text.length < max_width) ? text :
                                  text.scan(regex).join(zero_width_space)
    end
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user)
    cookies.permanent[:remember_token] = user.remember_token
    self.current_user = user
  end

  def signed_in?
    !current_user.nil?
  end

  def current_user?(user)
  	user == current_user	
  end

  def current_user=(user)
    @current_user = user
  end

  def current_user
    @current_user ||= User.find_by_remember_token(cookies[:remember_token])
  end

  def sign_out
    self.current_user = nil
    cookies.delete(:remember_token)
  end

  def redirect_back_or(default)
    redirect_to(session[:return_to] || default)
    session.delete(:return_to)
  end

  def store_location
    session[:return_to] = request.url
  end

  def signed_in_user
    unless signed_in?
      store_location
      flash[:danger] = "Please sign in."
      redirect_to signin_url
    end
  end  
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
  def gravatar_for(user, options = {size: 50, cssclass: ""})
  	gravatar_id		= Digest::MD5::hexdigest(user.email.downcase)
  	size			= options[:size]
  	cssclass		= options[:cssclass]
  	gravatar_url	= "https://secure.gravatar.com/avatar/#{gravatar_id}?s=#{size}"
  	image_tag(gravatar_url, alt: user.name, class: "#{cssclass}")
  end
end

app/views/layouts/_footer.html.slim
footer.navbar
	/.navbar-fixed-bottom
	p.navbar-text.pull-right
		| © 2013 
		= link_to 'education', root_path
		|  in russia

app/views/layouts/_header.html.slim
nav.navbar.navbar-inverse role="navigation"
	.navbar-header
		button.navbar-toggle type="button" data-toggle="collapse" data-target=".navbar-ex1-collapse"
			span.sr-only Toggle navigation
			span.icon-bar
			span.icon-bar
			span.icon-bar
		= link_to "Образование #", root_path, id: "logo", class: "navbar-brand"

	.collapse.navbar-collapse.navbar-ex1-collapse
		ul.nav.navbar-nav.navbar-right
			li = link_to "Помощь", help_path
			- if signed_in?
				li.dropdown.active
					a.dropdown-toggle href="#" data-toggle="dropdown"
						= current_user.name
						|  
						b.caret
					ul.dropdown-menu
						li = link_to "Профиль"	, edit_user_path(current_user)
						li = link_to "Выход"	, signout_path, method: "delete"
			- else
				li.active = link_to "Войти", signin_path

app/views/layouts/application.html.slim
doctype html
html
	head
		title = title(yield(:title))
		= stylesheet_link_tag    "application", :media => "all"
		= javascript_include_tag "application"
		= csrf_meta_tags
		/![if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]
	body
		/ navigation
		= render "layouts/header"

		/ content
		.container
			- flash.each do |key, value|
				.alert{class = "alert-#{key}"}
					button.close type="button" data-dismiss="alert" aria-hidden="true" &times; 
					p = value
			= yield

		/ footer
		= render "layouts/footer"
		= debug(params) if Rails.env.development?

app/views/microposts/_micropost.html.slim
li
	span.content = wrap micropost.content
	span.timestamp
		| отправлено 
		= time_ago_in_words(micropost.created_at)
		|  назад.
	- if current_user?(micropost.user)
		|  
    	= link_to "delete", micropost, method: :delete, data: { confirm: "You sure?" }, title: micropost.content

app/views/shared/_error_messages.html.slim
- if object.errors.any?
	div id="error_explanation"
		.alert.alert-error
			| The form contains
			= pluralize(object.errors.count, "error")
			| .
		ul
			- object.errors.full_messages.each do |msg|
				li = msg

app/views/shared/_feed.html.slim
- if @feed_items.any?
	ol.microposts
    	= render partial: 'shared/feed_item', collection: @feed_items
	= will_paginate @feed_items

app/views/shared/_feed_item.html.slim
li id="#{feed_item.id}"
	= link_to gravatar_for(feed_item.user), feed_item.user
	span.user
		= link_to feed_item.user.name, feed_item.user
	span.content = wrap feed_item.content
	span.timestamp
		| Posted 
		= time_ago_in_words(feed_item.created_at)
		|  ago.

app/views/shared/_micropost_form.html.slim
= form_for(@micropost) do |f|
	= render 'shared/error_messages', object: f.object
	.field.col-lg-4
		= f.text_area :content, placeholder: "Compose new micropost..."
		= f.submit "Post", class: "btn btn-large btn-primary form-control"

app/views/shared/_user_info.html.slim
= link_to gravatar_for(current_user, size: 50), user_path(current_user)
h1 = current_user.name
span = link_to "view my profile", current_user
span = pluralize(current_user.microposts.count, "micropost")

app/views/static_pages/help.html.slim
= provide(:title, 'Help')
h1 StaticPages#help
p Find me in app/views/static_pages/help.html.erb

app/views/static_pages/home.html.slim
= provide(:title, 'Home')
- if signed_in?
	.row
		aside.col-lg-3
			section
				= render 'shared/user_info'
			section
				= render 'shared/micropost_form'
		section.col-lg-9
			h3 microposts
			= render 'shared/feed'
- else
	.center.jumbotron
		h1 Добро пожаловать на образование # РФ
		h2 Это домашняя страница сайта образование в РФ
		= link_to "Зарегистрируйся!", signup_path, class: "btn btn-primary btn-lg"
	= link_to image_tag("rails.png", alt: "Rails"), 'http://rubyonrails.org/'

app/views/users/_user.html.slim
tr
	td
		= link_to gravatar_for(user, cssclass: "media-object", size: 50), user, class: "pull-left"
	td
		h4.media-heading = link_to user.name, user
		= user.email
	td
		- if current_user.admin? && !current_user?(user) 
    		= link_to "Удалить", user, method: :delete, data: { confirm: "You sure?" }
    	- elsif user.admin
    		| Администратор

app/views/users/edit.html.slim
= provide(:title, "Изменить профиль")


.row
	aside.col-lg-3
			section
				= gravatar_for(@user, size: 150)
    			a href="http://gravatar.com/emails" изменить
	.col-lg-6
		h1 Изменить профиль
		= form_for(@user) do |f|
			= render 'shared/error_messages', object: f.object
			.form-group
				= f.label		:name
				= f.text_field	:name, class: "form-control"
			.form-group
				= f.label		:email
				= f.text_field	:email, class: "form-control"
			.form-group
				= f.label			:password
				= f.password_field	:password, class: "form-control"
			.form-group
				= f.label			:password_confirmation, "Confirm Password"
				= f.password_field	:password_confirmation, class: "form-control"
			.form-group
				= f.submit "Сохранить", class: "btn btn-large btn-primary form-control"

app/views/users/index.html.slim
= provide(:title, "Все пользователи")
h1 Все пользователи
.row
	.col-lg-12
		= will_paginate @users, renderer: BootstrapPagination::Rails, bootstrap: 3
		table.table
			= render @users
		= will_paginate @users, renderer: BootstrapPagination::Rails, bootstrap: 3

app/views/users/new.html.slim
= provide(:title, 'Регистрация')
.row
	h1 Регистрция
	p Зарейгистрируйся и получи печенюшку
	.col-lg-6.col-lg-offset-3
		= form_for(@user) do |f|
			= render 'shared/error_messages', object: f.object
			.form-group
				= f.label :name
				= f.text_field :name, class: "form-control"
			.form-group
				= f.label :email
				= f.text_field :email, class: "form-control"
			.form-group
				= f.label :password
				= f.password_field :password, class: "form-control"
			.form-group
				= f.label :password_confirmation, "Confirmation"
				= f.password_field :password_confirmation, class: "form-control"
			.form-group
				= f.submit "Create my account", class: "btn btn-large btn-primary form-control"

app/views/users/show.html.slim
= provide(:title, @user.name)
.row
	aside.col-lg-3
		section
			= gravatar_for(@user, size: 150, cssclass: "thumbnail")
	.col-lg-6
		h1 = @user.name
		- if @user.microposts.any?
			h3
				| Сообщения (
				= @user.microposts.count
				| )

			ol.microposts
				= render @microposts
			= will_paginate @microposts